const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function setup(){const context={window:{},WebSocket:{OPEN:1}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../sales_agent/static/cascade-controller.js'),'utf8'),context);const sent=[],tracks=[{enabled:true}],states=[];const c=new context.window.CascadeController({status:s=>states.push(s),error(){},transcript(){}});c.enabled=true;c.ready=true;c.generation=3;c.socket={readyState:1,send:s=>sent.push(JSON.parse(s))};c.stream={getAudioTracks:()=>tracks};return {c,sent,tracks,states};}
test('interruption stops every queued audio node and leaves microphone enabled',()=>{const {c,sent,tracks}=setup();let stopped=0;c.nodes.add({stop(){stopped++;},disconnect(){}});c.interrupt();assert.equal(stopped,1);assert.equal(c.nodes.size,0);assert.equal(tracks[0].enabled,true);assert.deepEqual(sent,[{type:'interrupt'}]);});
test('cancelled generation audio is discarded including packets before acknowledgement',()=>{const {c}=setup();let played=0;c.play=()=>played++;c.interrupt();c.message({type:'audio',generation:3});assert.equal(played,0);c.message({type:'interrupted',generation:4});c.message({type:'audio',generation:3});assert.equal(played,0);c.message({type:'audio',generation:4});assert.equal(played,1);});
test('pause cannot disable microphone during model speech',()=>{const {c,tracks}=setup();c.pause();assert.equal(tracks[0].enabled,true);});

test('done waits for all queued audio before acknowledging playback completion',()=>{const {c,sent,states}=setup();const node={};c.nodes.add(node);c.message({type:'done',generation:3});assert.equal(sent.length,0);assert.equal(c.nodes.size,1);c.nodes.delete(node);c.playbackFinished();assert.deepEqual(sent,[{type:'playback_finished',generation:3}]);assert.equal(states.at(-1),'listening');c.playbackFinished();assert.equal(sent.length,1);});

test('only current generation can focus a recommended product',()=>{const {c}=setup();const focused=[];c.focus=id=>focused.push(id);c.message({type:'focus',generation:2,product_id:'old'});c.message({type:'focus',generation:3,product_id:'vista-phone-8'});assert.deepEqual(focused,['vista-phone-8']);});
